# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
default_velocity_scaling_factor: 0.8
default_acceleration_scaling_factor: 0.3

joint_limits:
  panda_joint1:
    has_velocity_limits: true
    max_velocity: 2.175
    has_acceleration_limits: true
    max_acceleration: 0.8
  panda_joint2:
    has_velocity_limits: true
    max_velocity: 2.175
    has_acceleration_limits: true
    max_acceleration: 0.8
  panda_joint3:
    has_velocity_limits: true
    max_velocity: 2.175
    has_acceleration_limits: true
    max_acceleration: 0.8
  panda_joint4:
    has_velocity_limits: true
    max_velocity: 2.175
    has_acceleration_limits: true
    max_acceleration: 0.8
  panda_joint5:
    has_velocity_limits: true
    max_velocity: 2.61
    has_acceleration_limits: true
    max_acceleration: 0.8
  panda_joint6:
    has_velocity_limits: true
    max_velocity: 2.61
    has_acceleration_limits: true
    max_acceleration: 0.8
  panda_joint7:
    has_velocity_limits: true
    max_velocity: 2.61
    has_acceleration_limits: true
    max_acceleration: 0.8